// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	OPENROUTER_API_KEY: "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";
	NODE_VERSION: "20.5.0";
	AI: Ai;
}
